model:
  base_learning_rate: 0.0008
  weight_decay: 0.0
  target: ldm.models.diffusion.ddpm.LatentDiffusion
  params:
    linear_start: 0.00085
    linear_end: 0.012
    num_timesteps_cond: 1
    log_every_t: 200
    timesteps: 1000
    first_stage_key: image
    cond_stage_key: caption
    image_size: 64
    channels: 4
    cond_stage_trainable: true
    conditioning_key: crossattn
    monitor: val/loss_simple_ema
    scale_factor: 0.18215
    use_ema: false
    embedding_reg_weight: 0.05
    unfreeze_model: false
    model_lr: 0.0
    use_layerwise_embedding: true
    use_ada_embedding: true
    composition_regs_iter_gap: 5
    composition_delta_reg_weight: 0.0001
    composition_prompt_mix_reg_weight: 0.002
    cls_prompt_mix_weight_max: 0.4
    clip_text_loss_weight: 0.0002
    scheduler_config:
      target: ldm.lr_scheduler.LambdaWarmUpCosineScheduler
      params:
        verbosity_interval: 0
        warm_up_steps: 500
        max_decay_steps: 4500
        lr_start: 0.01
        lr_max: 1.0
        lr_min: 0.25
    personalization_config:
      target: ldm.modules.embedding_manager.EmbeddingManager
      params:
        placeholder_strings:
        - z
        initializer_words:
        - indian girl
        initializer_weights:
        - - 1.0
          - 2.0
        initializer_neg_words: []
        num_vectors_per_token: 1
        progressive_words: false
        use_layerwise_embedding: true
        layerwise_lora_rank_token_ratio: 2
        ada_emb_weight: 0.5
        composition_delta_reg_iter_gap: 10
        embedding_manager_ckpt: ''
        cls_delta_token: null
    unet_config:
      target: ldm.modules.diffusionmodules.openaimodel.UNetModel
      params:
        image_size: 32
        in_channels: 4
        out_channels: 4
        model_channels: 320
        attention_resolutions:
        - 4
        - 2
        - 1
        num_res_blocks: 2
        channel_mult:
        - 1
        - 2
        - 4
        - 4
        num_heads: 8
        use_spatial_transformer: true
        transformer_depth: 1
        context_dim: 768
        use_checkpoint: true
        legacy: false
    first_stage_config:
      target: ldm.models.autoencoder.AutoencoderKL
      params:
        embed_dim: 4
        monitor: val/rec_loss
        ddconfig:
          double_z: true
          z_channels: 4
          resolution: 512
          in_channels: 3
          out_ch: 3
          ch: 128
          ch_mult:
          - 1
          - 2
          - 4
          - 4
          num_res_blocks: 2
          attn_resolutions: []
          dropout: 0.0
        lossconfig:
          target: torch.nn.Identity
    cond_stage_config:
      target: ldm.modules.encoders.modules.FrozenCLIPEmbedder
      params:
        last_layer_skip_weight: 0.5
    ckpt_path: models/stable-diffusion-v-1-5/v1-5-pruned.ckpt
data:
  target: main.DataModuleFromConfig
  params:
    batch_size: 2
    num_workers: 2
    wrap: false
    train:
      target: ldm.data.personalized.PersonalizedBase
      params:
        size: 512
        set: train
        repeats: 100
        placeholder_token: z
        broad_class: 1
        cls_delta_token: null
        cls_distill_token: null
        num_compositions_per_image: 1
        rand_scaling_range:
        - 0.7
        - 1
    validation:
      target: ldm.data.personalized.PersonalizedBase
      params:
        size: 512
        set: val
        repeats: 10
        placeholder_token: z
        broad_class: 1
        cls_delta_token: null
        cls_distill_token: null
--use_cls_token: null
